baseURL = 'https://rhariady.xyz/'
languageCode = 'en-us'
title = 'rhariady.xyz'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
  author = 'Ricky Hariady'

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rickyhariady"